version: '3.7'
services:
  db:
    image: postgres:15
    container_name: habit_all
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: habit_all_cache

  atomic_habits:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habit_all_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command:
      - "docker/app.sh"
    ports:
      - 7777:8000

  celery:
    build: .
    container_name: habit_all_celery
    env_file:
      - .env-non-dev
    command:
      - "docker/celery.sh"
    depends_on:
      - habit_all

  celery-beat:
    build: .
    container_name: habit_all_celery_beat
    env_file:
      - .env-non-dev
    command:
       - "docker/celery_beat.sh"
    depends_on:
      - habit_all
volumes:
  postgresdata: